### ISSUE TITLE
currency breaks updatePortf

### ISSUE THREAD

**Issue by paglos** [braverock/blotter#103] opened 2020-03-03 23:47 UTC
Following code works on blotter 0.9.1695, but not on 0.14.7
```
library(quantstrat)
library(quantmod)

currency("USD")
currency("EUR")

exchange_rate("EURUSD", currency="EUR", counter_currency="USD", src=list(name='EUR/USD', src='oanda'))


getSymbols("EURUSD", from="2019-11-01",to="2019-11-07")
colnames(EURUSD) <- "price"

initPortf("PF1", symbols= c("EURUSD"), currency="USD",initDate="2019-11-04")
initAcct("myacct", portfolios="PF1", initDate="2019-11-04",currency="USD", initEq=200000)
initOrders(portfolio="PF1",initDate="2019-11-04")

addTxn("PF1", Symbol="EURUSD", TxnDate="2019-11-05", TxnPrice = 1.24650, TxnQty= 100000)
addTxn("PF1", Symbol="EURUSD", TxnDate="2019-11-05", TxnPrice = 1.24620, TxnQty=-100000)

updatePortf("PF1",   Dates = "2019-11-04::2019-11-05")
```
**Error in NextMethod(.Generic) : 
  number of items to replace is not a multiple of replacement length**

**Comment by jaymon0703** [comment] 2020-03-04 19:36
Hi @paglos the `amzn_test.R` demo works on 0.14.7 and shares the most similar structure to your example code. In order to reproduce your error could you share your source data?

**Comment by joshuaulrich** [comment] 2020-03-05 03:10
Here's a self-contained example.  I'm not sure an example with `data(amzn)` would work though.  This may be an issue with daily data (`"Date"` class) interacting with POSIXct.

```r
require(blotter)

currency(c("USD", "EUR"))
exchange_rate("EURUSD", "EUR", "USD")

EURUSD <-
  xts(c(1.116014, 1.11654, 1.116545, 1.11534, 1.110306, 1.10765, 1.106165),
      timeBasedSeq("2019-11-01/2019-11-07"), dimnames = list(NULL, "price"))


initPortf("PF1", "EURUSD", 0, "2019-11-04")
initAcct("myacct", "PF1", "2019-11-04", initEq = 200000)

addTxn("PF1", "EURUSD", "2019-11-05",  100000, 1.24650)
addTxn("PF1", "EURUSD", "2019-11-05", -100000, 1.24620)

updatePortf("PF1", NULL, "2019-11-04::2019-11-05")
```

Note that you get a different error if the column name of the `EURUSD` object is not `"price"`.

```r
require(blotter)

currency(c("USD", "EUR"))
exchange_rate("EURUSD", "EUR", "USD")

EURUSD <-
  xts(c(1.116014, 1.11654, 1.116545, 1.11534, 1.110306, 1.10765, 1.106165),
      timeBasedSeq("2019-11-01/2019-11-07"), dimnames = list(NULL, "foo"))


initPortf("PF1", "EURUSD", 0, "2019-11-04")
initAcct("myacct", "PF1", "2019-11-04", initEq = 200000)

addTxn("PF1", "EURUSD", "2019-11-05",  100000, 1.24650)
addTxn("PF1", "EURUSD", "2019-11-05", -100000, 1.24620)

updatePortf("PF1", NULL, "2019-11-04::2019-11-05")
# Error in getPrice(get(Symbol, pos = env), symbol = symbol, prefer = prefer) : 
#   subscript out of bounds, no price was discernible from the data
```

**Comment by jaymon0703** [comment] 2020-03-05 03:44
Thanks @joshuaulrich. Do you also get this error for your original self-contained example?

```
Error in attributes(xx) <- c(attributes(xx), dot.attrs) : 
  length of 'dimnames' [2] not equal to array extent
In addition: Warning message:
In max(start, as.numeric(s), na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
Called from: .xts(rep(NA, length(i)), .index(x)[i], dimnames = list(NULL, 
    colnames(x)))
```
Originates in line 94 of .updatePosPL.

**Comment by joshuaulrich** [comment] 2020-03-07 14:02
@jaymon0703 I'm not sure what you mean.  My first example replicates the error in the OP.  My second example throws the error in the comment at the bottom of the example.

For what it's worth, here's my `sessionInfo()`:

```r
R> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] blotter_0.14.7               PerformanceAnalytics_1.5.2.2
[3] FinancialInstrument_1.3.1    quantmod_0.4-16             
[5] TTR_0.23-5                   xts_0.12-0                  
[7] zoo_1.8-5                   

loaded via a namespace (and not attached):
[1] compiler_3.6.1   curl_4.2         codetools_0.2-16 grid_3.6.1      
[5] iterators_1.0.12 foreach_1.4.7    boot_1.3-20      lattice_0.20-38 
[9] quadprog_1.5-7  
```

**Comment by jaymon0703** [comment] 2020-03-09 17:56
Apologies @joshuaulrich my bad...i think it was a case of premature debugging or debugging in a dirty environment.

@paglos if you use a timestamp in your example the code will work just fine. This would make sense to do for intraday transactions.

```r
addTxn("PF1", "EURUSD", "2019-11-05 10:00:00",  100000, 1.24650)
addTxn("PF1", "EURUSD", "2019-11-05 11:00:00", -100000, 1.24620)
```

The error occurs in line 233. The problem starts in line 213 because we are merging objects of differing lengths. This can be avoided with more granularity in the transaction timestamps for intraday transactions.

**Comment by jaymon0703** [comment] 2020-03-22 02:18
hi @paglos can we close this issue?

**Comment by fmoudoute** [comment] 2024-09-09 04:10
Hi, i am having the same error , been investigating for days :
`Error in is.na(CcyMult) && !is.na(FXrate) : 
  'length = 7' in coercion to 'logical(1)'`
  
  What is the solution that was found please ?

**Comment by untdacca** [comment] 2024-09-09 13:55
Ranma 1/2


Thanks,
Ian Fayorsey

**Comment by braverock** [comment] 2024-09-09 14:54
@untdacca please provide a reproducible example.  It is likely that your transactions or your instrument definitions are malformed.

**Comment by braverock** [comment] 2024-09-09 14:55
@fmoudoute the solution here was to put timestamps on the trades.  the solution to your problem might be different.  please provide a reproducible example to demonstrate the problem.

**Comment by joshuaulrich** [comment] 2024-09-09 15:42
@braverock my example reproduces the error. I'm looking into it now.

**Comment by joshuaulrich** [comment] 2024-09-09 18:05
It looks like there are a couple issues. One is that `FXrate` can be an xts object with multiple rows, which causes the `if()` statement to fail. That's an easy fix.

Another issue is when two transactions have the same timestamp. There's a check in `addTxn()` to prevent adding a transaction with a *prior* timestamp, but equal timestamps are allowed. I don't remember for sure, but I think duplicate timestamps aren't supported. Is that correct @braverock?

This is a problem because of how xts handles subsetting when an object has duplicate index values and `i` has duplicate values that are the same as the duplicate index values in `x`. For example:

```r
x <-
   structure(c(1.1, 1.2, 1.3, 1.4),
             dim = c(4L, 1L), dimnames = list(NULL, "price"),
             index = structure(c(1572739200, 1572825600, 1572912000, 1572912000),
                               tzone = "UTC",
                               tclass = "Date"),
             class = c("xts", "zoo"))

x
##               price
## 2019-11-03 1.1
## 2019-11-04 1.2
## 2019-11-05 1.3
## 2019-11-05 1.4

(y <- x[index(x),])
##               price
## 2019-11-03 1.1
## 2019-11-04 1.2
## 2019-11-05 1.3
## 2019-11-05 1.3
## 2019-11-05 1.4
## 2019-11-05 1.4

```

The object and index have 2 observations on 2019-11-05. It isn't immediately obvious, but it makes sense that `y` would have 4 observations for 2019-11-05. `y[3:4]` are from matching `i[3]` with `x[3:4]`. `y[5:6]` are from matching `i[4]` with `x[3:4]`.

**Comment by fmoudoute** [comment] 2024-09-10 03:09
> !is.na(FXrate)

Hey, the issue was indeed that the FXRate can be an XTS object with multiple rows. In the updatePosPL method, I replace  `	if(is.na(CcyMult) && !is.na(FXrate)) {...` with `	if(is.na(CcyMult) && any(!is.na(FXrate))) {...` and the problem is fixed.

**Comment by joshuaulrich** [comment] 2024-09-10 03:28
@fmoudoute thanks for investigating. I already fixed this in commit https://github.com/braverock/blotter/commit/a076aaddaf82ab7888c1fd0e46eae0eaba2cde52.

**Comment by fmoudoute** [comment] 2024-09-10 03:34
> @fmoudoute thanks for investigating. I already fixed this in commit [a076aad](https://github.com/braverock/blotter/commit/a076aaddaf82ab7888c1fd0e46eae0eaba2cde52).

@joshuaulrich just to make sure I understand please, is the library supporting this combination:

1. Instrument trading in CNY
2. Trade executed with a price in USD
3. Reporting (portfolio and account) in CNY 
So far from what i see, the transaction is recorded in USD indeed, but he portfolio Summary seems to be showing CNY metrics.

**Comment by joshuaulrich** [comment] 2024-09-10 03:43
@fmoudoute would you please create a new issue with a [minimal, reproducible example](http://stackoverflow.com/q/5963269/271616) that demonstrates the behavior you see? It may or may not be related to this issue. It will be much easier to debug if you provide code that we can run that illustrates the behavior.

**Comment by fmoudoute** [comment] 2024-09-11 03:12
@joshuaulrich , sure, I have prepared the following to illustrate my problem:

```r
### Getting instrument prices (And adjusting time to 3pm - arbitrary)

getSymbols("000651.SZ", src="yahoo", from="2024-01-01", to="2024-09-09")
`000651.SZ` <- data.frame(Date = index(`000651.SZ`), coredata(`000651.SZ`))
`000651.SZ`$DateTime <- as.POSIXct(paste(`000651.SZ`$Date, "15:00:00"), format = "%Y-%m-%d %H:%M:%S")
`000651.SZ`$Date <- NULL
`000651.SZ` <- `000651.SZ`[, c("DateTime", colnames(`000651.SZ`)[1:6])]
`000651.SZ` <- as.xts(`000651.SZ`)

### Defining instrument using FinancialInstrument's stock method
stock("000651.SZ", currency = "CNY")

### Deleting account and portfolio if they exist
rm("account.Strategy1",pos=.blotter)
rm("portfolio.Strategy1",pos=.blotter)
suppressWarnings(rm("account.Strategy1","portfolio.Strategy1",pos=.blotter))
suppressWarnings(rm("order_book.Strategy1",pos=.strategy))

### Defining instrument using FinancialInstrument's currency method
currency(c("CNY", "USD"))

### Setting syst' timezone
Sys.setenv(TZ ="Asia/Taipei")

### portfolio initiation date with TimeZone
intitation.Date <- as.POSIXct(paste("2024-07-21", "3:00 PM"), format = "%Y-%m-%d %I:%M %p", tz="Asia/Taipei", usetz=TRUE)`

### Portfolio initial capital
PortfolioCapital <- 12000000 #this amount is in USD

### Initiating portfolio and account
initPortf("Strategy1", symbols='000651.SZ', initDate = intitation.Date, currency = "USD")
initAcct("Strategy1", portfolios = "Strategy1", initEq = PortfolioCapital, initDate = intitation.Date, currency = "USD")
addPortfInstr(Portfolio = "Strategy1", symbols = '000651.SZ')

### Fetch FX rate data (assuming FX rate data is available)
getSymbols("CNY=X", src="yahoo", from="2018-01-01", to="2024-09-09")
`CNY=X` <- na.approx(object = `CNY=X`)
`CNY=X` <- data.frame(Date = index(`CNY=X`), coredata(`CNY=X`))
`CNY=X`$DateTime <- as.POSIXct(paste(`CNY=X`$Date, "15:00:00"), format = "%Y-%m-%d %H:%M:%S")
`CNY=X`$Date <- NULL
`CNY=X` <- `CNY=X`[, c("DateTime", colnames(`CNY=X`)[1:6])]
`CNY=X` <- as.xts(`CNY=X`)

### Assign the symbol as CNY/USD for use in Blotter
assign("USD/CNY", `CNY=X`)
assign("USDCNY", `CNY=X`)
assign("CNY/USD", 1 /Cl(`USD/CNY`))
assign("CNYUSD", 1 /Cl(`USD/CNY`))
exchange_rate("CNYUSD")
exchange_rate("USDCNY")

### Preparing transaction - NB: We are trading on swap so booking trade in USD 
### This means that daily valuation will/should be impacted by both currency (USDCNY) moves and equity move
trade_qty <- 250000
price_cny <- 38.50  # Price in RMB
fx_rate <- 7.12     # FX rate (1 USD = 7 RMB)
price_usd <- price_cny / fx_rate  # Converted price in USD
TradeDate <-as.POSIXct("2024-07-22 3:00 PM", format = "%Y-%m-%d %I:%M %p", tz="Asia/Taipei", usetz=TRUE)

getInstrument('000651.SZ')

### Adding transaction
addTxn(Portfolio="Strategy1", Symbol="000651.SZ", TxnDate=TradeDate,
       TxnPrice=price_usd, TxnQty=trade_qty, TxnFees=0, Currency="USD")

### Updating Portfolio
updatePortf(Portfolio="Strategy1", Dates="2024-07-22 15:00:00/2024-09-06 15:00:00")
```
I was hoping that I could book the trade in USD and the Blotter would update the valuation based on FX move and Instrument Closing prices.

Is it possible and am I not doing it properly, or is it not possible (a bit too stretch?)
N.B. I did more exploratory work and by booking the trade in CNY (the instrument currency) and keeping the portfolio in USD, I get the right valuation metrics. But I could book the trade in another currency and having Blotter convert it to CNY at the valuation step.
![image](https://github.com/user-attachments/assets/aec856ae-dcaf-4ea6-8b04-4af5709fcbac)

**Comment by joshuaulrich** [comment] 2024-09-11 22:20
@fmoudoute I created a new issue because your question is not related to this issue.

**Closed as completed** 2024-09-11 22:20 UTC

**Comment by fmoudoute** [comment] 2024-09-12 01:04
> @fmoudoute I created a new issue because your question is not related to this issue.

@joshuaulrich , sure, understood, thanks a lot!
