### ISSUE TITLE
amzn_test demo error

### ISSUE THREAD

**Issue by evelynmitchell** [braverock/blotter#33] opened 2016-07-10 14:50 UTC
> updateAcct("amzn_acct",Dates="2010-01-14")
> Error in match.arg(on, c("years", "quarters", "months", "weeks", "days",  : 
>   'arg' should be one of “years”, “quarters”, “months”, “weeks”, “days”, “hours”, “minutes”, “seconds”, “milliseconds”, “microseconds”, “ms”, “us”

I believe  the fix is to remove the Dates argument from both updateAcct and updatePortf.

**Comment by joshuaulrich** [comment] 2016-07-10 16:09
This is caused by an `xts::endpoints` bug that was introduced in https://github.com/joshuaulrich/xts/commit/d5d7c6aa95fa1ef7cb0c9ce661565ae1d3ad5d9f and fixed in https://github.com/joshuaulrich/xts/commit/3f5570ae515c4efa1e08cd93dffc725f4fec3f73.

**Closed as completed by joshuaulrich** 2016-07-10 16:09 UTC
